// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77K97YI1a0DV5xYLbhHpxL_r5QlL6F3E',
    appId: '1:940080919575:web:84f5dbec2ec3c9c5be9852',
    messagingSenderId: '940080919575',
    projectId: 'tv-channels-d4a59',
    authDomain: 'tv-channels-d4a59.firebaseapp.com',
    storageBucket: 'tv-channels-d4a59.appspot.com',
    measurementId: 'G-FSVMHHFN40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBmVB5pTVIcjdg4SaPOruzC4CEOJKEZk',
    appId: '1:940080919575:android:37f86762b3c85260be9852',
    messagingSenderId: '940080919575',
    projectId: 'tv-channels-d4a59',
    storageBucket: 'tv-channels-d4a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3oPFHVr8Bpq1afXnmZKR6bYX-NadbNA',
    appId: '1:940080919575:ios:e857588d9ccaa3eebe9852',
    messagingSenderId: '940080919575',
    projectId: 'tv-channels-d4a59',
    storageBucket: 'tv-channels-d4a59.appspot.com',
    iosBundleId: 'com.example.tvchan',
  );
}
